version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finalproject
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nest_network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '7001:7001'
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - nest_network
    command: npm run start:dev
networks:
  nest_network:
    driver: bridge
volumes:
  postgres_db:
    driver: local    
